### ISSUE TITLE
evaluate if stat if empty

### ISSUE THREAD

**Issue by pandamasta** [pandamasta/bitiso-django#1]
$ python manage.py updateTorrents
Success during urlopen
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/owel/git/bitiso/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/owel/git/bitiso/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/owel/git/bitiso/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/owel/git/bitiso/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/owel/git/bitiso/bitiso-django-new/torrent/management/commands/updateTorrents.py", line 32, in handle
    trackerStatsSL.write(trackerStats.read().decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by pandamasta** [comment]
Function removed
